# 一下配置可以在子配置文件中被覆盖
spring:
  datasource:
    default-db-key: self
    database-load-activate: true # 是否启用数据库加载
    multi-db:
      - master: # 数据源的key
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: osd_hr_workbench_rw@public#ob_public_dev_40000
          password: 'MQ8!aQnVqt4WU#wz'
          url: jdbc:mysql://ob-public-dev-40000.chj.cloud:3306/osd_hr_workbench?autoCommit=true&autoReconnect=true&useUnicode=true&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&yearIsDateType=false&serverTimezone=Asia/Shanghai&trackSessionState=true
      - self:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: root
          url: jdbc:mysql://192.168.47.130:3306/demo?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&serverTimezone=Asia/Shanghai&useTimezone=true


mybatis:
  #1.classpath：只会到你的classes路径中查找找文件。
  #2.classpath*：不仅会到classes路径，还包括jar文件中(classes路径)进行查找。
  mapper-locations: classpath*:/**/*Mapper.xml    # mapper映射文件位置
  type-aliases-package: com.**.entity    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true #开启将带有下划线的表字段 映射为驼峰格式的实体类属性